title: Title
url: https://www.open.gov.sg
favicon: /images/lean on me logo.svg
colors:
  primary-color: "#fdb400"
  secondary-color: "#f72b60"
  media-colors:
    - title: media-color-one
      color: "#35a1f4"
    - title: media-color-two
      color: "#f15535"
    - title: media-color-three
      color: "#2ec6ba"
    - title: media-color-four
      color: "#141b41"
    - title: media-color-five
      color: "#ffffff"
description: An Isomer site of the Singapore Government
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d32hj0xgtb86qn.amplifyapp.com
prod: https://master.d32hj0xgtb86qn.amplifyapp.com
facebook-pixel: ""
resources_name: all-resources
shareicon: /images/lean on me logo.svg
is_government: false
google_analytics: ""
google_analytics_ga4: ""
linkedin-insights: ""
